name: Docker Scout Scan and Push

on: [push]

jobs:
  scan-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME  }}/gohello:latest
          push: false

      - name: Docker Scout Scan
        id: scout-scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKER_HUB_USERNAME  }}/gohello:latest

      - name: Check scan results
        run: |
          if [ "${{ steps.scout-scan.outputs.vulnerabilities_found }}" != "0" ]; then
            echo "Critical vulnerabilities found, skipping push."
            exit 1
          fi

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME  }}/gohello:latest
          push: true
